version: '3.4'

secrets:
  geth:
    external: true
  postgres:
    external: true

volumes:
  postgres:

networks:
  back:

services:

  salesync:
    image: ckmill_salesync:latest
    deploy:
      mode: global
      restart_policy:
        condition: any
    depends_on:
      - postgres
    secrets:
      - postgres
    environment:
      - ETH_PROVIDER
      - ETH_ADDRESS
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=ckmill
      - PGDATABASE=ckmill
      - PGPASSFILE=/run/secrets/postgres
    volumes:
      - type: bind
        source: ../build/salesync.bundle.js
        target: /root/salesync.bundle.js
      - type: bind
        source: /tmp/ipc
        target: /tmp/ipc
    networks:
      - back

  kittysync:
    image: ckmill_kittysync:latest
    deploy:
      mode: global
      restart_policy:
        condition: any
    depends_on:
      - postgres
    secrets:
      - postgres
    environment:
      - ETH_PROVIDER
      - ETH_ADDRESS
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=ckmill
      - PGDATABASE=ckmill
      - PGPASSFILE=/run/secrets/postgres
    volumes:
      - type: bind
        source: ../build/kittysync.bundle.js
        target: /root/kittysync.bundle.js
      - type: bind
        source: /tmp/ipc
        target: /tmp/ipc
    networks:
      - back

  postgres:
    image: postgres:10
    deploy:
      mode: global
      restart_policy:
        condition: any
    secrets:
      - postgres
    environment:
      - POSTGRES_USER=ckmill
      - POSTGRES_DB=ckmill
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - back

