version: '3.4'

secrets:
  postgres:
    external: true

volumes:
  postgres:
  ethprovider_ipc:

networks:
  back:

services:

  salesync:
    image: ckmill_salesync:latest
    deploy:
      mode: global
    volumes:
      - ethprovider_ipc:/tmp/ipc

  kittysync:
    image: ckmill_kittysync:latest
    deploy:
      mode: global
    volumes:
      - ethprovider_ipc:/tmp/ipc

  postgres:
    image: postgres:10
    deploy:
      mode: global
    secrets:
      - postgres
    environment:
      - POSTGRES_USER=ckmill
      - POSTGRES_DB=ckmill
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - back

